version: "3.7"

networks:
  app_net:

services:
  postgres_service:
    build: ./postgres_service
    container_name: "postgres_server"
    env_file:
      # sets the default password for user postgres
      - ./postgres_service/postgres.env
    networks:
      app_net:
    ports:
      - "15432:5432"
    volumes:
      - ../db:/var/lib/postgresql/data

  php_service:
    build: ./php_service
    container_name: "php_server"
    depends_on:
      - postgres_service
    env_file:
      - ./php_service/php.env
    networks:
      app_net:
    ports:
      - "9090:9000"
    volumes:
      - ../app:/var/www/app

  nginx_service:
    build: ./nginx_service
    container_name: "nginx_server"
    depends_on:
      - php_service
    env_file:
      - ./nginx_service/nginx.env
    networks:
      app_net:
    ports:
      - "8080:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/project_error.log:/var/log/nginx/project_error.log
      - ../nginx/project_access.log:/var/log/nginx/project_access.log
      - ../app:/var/www/app

  pgadmin_service:
    build: ./pgadmin_service
    container_name: "pgadmin_server"
    depends_on:
      - postgres_service
    networks:
      app_net:
    env_file:
      # sets the default user/password
      # and changes the default listen port 81
      - ./pgadmin_service/pgadmin.env
    ports:
      # changing container default listen port to 81
      # (so it doesn't collide with nginx service)
      - "16543:81"
    volumes:
      # Change manually:
      # host directory must be owned by uid:5050, gid:5050
      # (sudo chown -R 5050:5050 <host_directory>)
      - ../pgadmin:/var/lib/pgadmin